<a href="https://colab.research.google.com/github/nazishjahan22/Lead-Generation/blob/main/baseball_500hits_Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

Import pandas as pd, thne we read the csv file called ‘500hits.csv’

In [ ]:
df= pd.read_csv("/content/500hits.csv", encoding='latin1')

In [ ]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

 Drop the columns ‘Players and ‘cs’

In [ ]:
df = df.drop(columns = ['PLAYER', 'CS'])

Select all rows and columns 0 through 12 (not including 13)  and assign it to X

In [ ]:
X = df.iloc[:, 0:13]

Select all rows : from column index 13, and assign it to y

In [ ]:
y = df.iloc[:,13]

Import train_test_split from sklearn.model_selection

In [ ]:
from sklearn.model_selection import train_test_split

Split the data into testing and train sets.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=17, test_size=0.2)

Check the snape or dimension of the data, .shape returns (rows, columns)

In [ ]:
X_train.shape

(372, 13)

In [ ]:
X_test.shape

(93, 13)

Import DecisionTreeClassifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

In [ ]:
dtc = DecisionTreeClassifier()

In [ ]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

Train the model on our data using the .fit()

In [ ]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

After traing we predict, i.e we evaluate our models performance using the test data.

In [ ]:
y_pred = dtc.predict(X_test)

Import the confusion_matrix function from scikit-learn.

It is used to evaluate classification models by comparing the predicted labels with the actual labels.

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[51 10]
 [10 22]]

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84        61
           1       0.69      0.69      0.69        32

    accuracy                           0.78        93
   macro avg       0.76      0.76      0.76        93
weighted avg       0.78      0.78      0.78        93

Return an array of numbers showing how important each feature was in buiding the decision tree “dtc”

In [ ]:
features = pd.DataFrame(dtc.feature_importances_, index = X.columns)

In [ ]:
features.head(15)

            0
YRS  0.014755
G    0.048566
AB   0.018795
R    0.094004
H    0.393911
2B   0.043260
3B   0.052175
HR   0.000000
RBI  0.094577
BB   0.056473
SO   0.036079
SB   0.051021
BA   0.096385

Higher values of ccp_alpha lead to more pruning in the decision tree.
This is part of cost-complexity pruning, which removes less important branches to help prevent overfitting.



ccp_alpha(Cost Complexity Pruning Alpha) is a parameter that controls how much the tree should be simplified.

In [ ]:
dtc2 = DecisionTreeClassifier(criterion='entropy', ccp_alpha= 0.04)

After adding the ccp_alpha, we train, test and evaluate again to see if theres improvement.

In [ ]:
dtc2.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.04, criterion='entropy')

In [ ]:
y_pred2 = dtc2.predict(X_test)

In [ ]:
print(confusion_matrix(y_test, y_pred2))

[[50 11]
 [ 9 23]]

In [ ]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.85      0.82      0.83        61
           1       0.68      0.72      0.70        32

    accuracy                           0.78        93
   macro avg       0.76      0.77      0.77        93
weighted avg       0.79      0.78      0.79        93

In [ ]:
features2 = pd.DataFrame(dtc2.feature_importances_, index = X.columns)

In [ ]:
features2.head(15)

            0
YRS  0.000000
G    0.000000
AB   0.000000
R    0.000000
H    0.837977
2B   0.000000
3B   0.000000
HR   0.000000
RBI  0.000000
BB   0.000000
SO   0.000000
SB   0.000000
BA   0.162023